# Generated by Django 4.1.2 on 2022-10-29 09:39

import django.core.validators
from django.db import migrations, models
import examprep1.musicapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), examprep1.musicapp.models.username_contains_validator]),
        ),
    ]
